In [13]:
class Animal:
    def __init__(self):
        print("Animal created")

    def whoAmI(self):
        print("Animal")

    def eat(self):
        print("Eating")

class Dog(Animal):
    def __init__(self):
        Animal.__init__(self)
        print("Dog created")
    
    def bark(self):
        print(' Dogs bark')
    
    def eat(self):
        print('New eating')

In [14]:
d = Dog()

Animal created
Dog created


In [15]:
d.eat()

New eating


In [16]:
x = 'abcd'

In [19]:
list('a')

['a']

In [21]:
def square(num):
    return num*num


In [22]:
a = lambda num : num*num


In [23]:
a(2)

4

In [26]:
list( map( lambda num: num*num*num  ,  [i for i in range(1,11)] ))

[1, 8, 27, 64, 125, 216, 343, 512, 729, 1000]

In [27]:
t = (1,2,3,4,5)

In [28]:
dog = ('sam', 'black')

In [29]:
from collections import namedtuple

In [30]:
Dog = namedtuple('Dog','age breed name')

In [32]:
d = Dog(12,'lab', 'sam')

In [33]:
d.name

'sam'

In [40]:
d1 = Dog(12,'lab', 'sam')

In [39]:
d1.age

12

In [41]:
Cylender = namedtuple('Cylender', 'height radius')

In [42]:
c = Cylender(10,2)

In [43]:
c.height

10

In [44]:
c.radius

2

In [46]:
c.count(10)

1

In [47]:
l  =[1,2,3,4,5]

In [49]:
c.index(10)

0

In [50]:
square

<function __main__.square>

In [51]:
c = Cylender(10,4)

In [52]:
def func(num):
    return num+2

In [53]:
func(2)

4

In [54]:
func(c.height)

12

In [67]:
d1 = {}

d1['a'] = 'A'
d1['b'] = 'B'

d2 = {}

d2['b'] = 'B'
d2['a'] = 'A'

d1 == d2

True

In [69]:
from collections import OrderedDict
d1 = OrderedDict()

d1['a'] = 'A'
d1['b'] = 'B'

d2 = OrderedDict()

d2['b'] = 'B'
d2['a'] = 'A'

d1 == d2

False

In [70]:
import numpy as np

In [71]:
l = [1,2,3,4]

In [72]:
narr1 = np.array(l)

In [73]:
type(narr1)

numpy.ndarray

In [74]:
narr1

array([1, 2, 3, 4])

In [75]:
l

[1, 2, 3, 4]

In [104]:
narr2 = np.arange(0,101)

In [105]:
narr2

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [78]:
narr3 = np.ones(10)

In [79]:
narr3

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [80]:
narr4 = np.zeros(5)

In [81]:
narr4

array([ 0.,  0.,  0.,  0.,  0.])

In [84]:
narr5 = np.eye(4)

In [85]:
narr5

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [98]:
narr6 = np.linspace(1,250,23)

In [99]:
narr6

array([   1.        ,   12.31818182,   23.63636364,   34.95454545,
         46.27272727,   57.59090909,   68.90909091,   80.22727273,
         91.54545455,  102.86363636,  114.18181818,  125.5       ,
        136.81818182,  148.13636364,  159.45454545,  170.77272727,
        182.09090909,  193.40909091,  204.72727273,  216.04545455,
        227.36363636,  238.68181818,  250.        ])

In [102]:
narr7 = np.random.randint(1,100,20)

In [103]:
narr7

array([62, 70, 27, 45, 97, 43, 27, 12, 66, 94, 28, 39, 54, 43, 16, 53, 43,
       89, 88, 84])

In [106]:
l = [1,2,3,4,5,6,7,8,9,10]

In [109]:
l[:]

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [115]:
l = '11122223333444555566'

In [116]:
from collections import Counter
c = Counter(l)

In [117]:
c

Counter({'1': 3, '2': 4, '3': 4, '4': 3, '5': 4, '6': 2})

In [119]:
c.most_common()

[('2', 4), ('3', 4), ('5', 4), ('1', 3), ('4', 3), ('6', 2)]